baseURL = 'http://composcleta.org/'
languageCode = 'en-us'

title = "Composcleta"
theme = "hugo-universal-theme"
#themesDir = "../.."

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false
